name: its new Build

on:
  workflow_dispatch:
  push:
    tags:
      
      - 'new'

jobs:
  run-ci:
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: true
      upload-tag: "new"
